#!/bin/sh

if [ $# -eq 0 ]
then
	p=`find -L ~/media -type f -not -path '*/\.*' | sort | dmenu -p file: -i -l 10`
else
	p="$(dbrowse)"
fi

if [ "$p" != "" ]
then
	c=`(echo xdg-open ; (dmenu_path | sed '/^xdg-open$/d')) | dmenu -p command:`
	if [ "$c" != "" ]
	then
		if [[ $c = *! ]]
		then
			$TERMINAL -e $SHELL -c "${c:0:-1} \"$p\" ; read"
		else
			$c "$p"
		fi
	fi
fi
